development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:p7dcfa52979100ec4d8f13639c5d66bda1913ac1a885449b22a2efcddaa124004@ec2-79-125-18-120.eu-west-1.compute.amazonaws.com:13329

