development:
  adapter: postgresql
  encoding: unicode
  database: pomo-tracking_development
  pool: 5
  username: andrei
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pomo-tracking_test
  pool: 5
  username: andrei
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: pomo-tracking_production
  pool: 5
  username: andrei
  password:
